const SUPABASE_URL="https://lxpjqvlphvjyygifedeb.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4cGpxdmxwaHZqeXlnaWZlZGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0MTMyMTMsImV4cCI6MjA5ODk4OTIxM30.9ovZlNQ-XKdSszZuMYb6PzRnXtX5eejuzBeqpKgkVnk";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
let authMode="login",activeFeed="para-ti",activeView="inicio",currentUser=null,currentProfile={},videos=[],observer,searchTimer;
const savedKey="livescroll8_saved_videos";

function safeUrl(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:""}catch{return""}}
function toast(message,type="ok"){$("#toast").textContent=message;$("#toast").className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$("#toast").className="toast",2600)}
function loading(btn,on,text="Cargando…"){btn.disabled=on;btn.dataset.text||=btn.textContent;btn.textContent=on?text:btn.dataset.text}
function saved(){try{return new Set(JSON.parse(localStorage.getItem(savedKey)||"[]"))}catch{return new Set()}}
function avatar(el,p){if(!el)return;el.innerHTML=p?.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(p?.avatar_emoji||"8")}
function authError(e){const m=String(e?.message||e);if(/invalid login/i.test(m))return"Correo o contraseña incorrectos.";if(/email not confirmed/i.test(m))return"Primero confirmá tu correo.";if(/network|fetch/i.test(m))return"No pudimos conectar. Revisá tu internet.";return m}
function showApp(open){$("#authScreen").classList.toggle("hidden",open);$("#mainApp").classList.toggle("open",open);$("#mainApp").setAttribute("aria-hidden",!open);if(open)boot()}

async function profile(id){let r=await sb.from("profiles").select("id,username,avatar_url,avatar_emoji,bio,points_balance,is_creator,is_creator_verified").eq("id",id).maybeSingle();if(r.error)r=await sb.from("profiles").select("id,username,avatar_url,avatar_emoji,bio,is_creator").eq("id",id).maybeSingle();return r.data||{}}
async function identity(){const r=await sb.auth.getUser();currentUser=r.data.user;if(!currentUser)return false;currentProfile=await profile(currentUser.id);avatar($("#topAvatar"),currentProfile);return true}

function card(v,i,likes){const p=v.profiles||{},url=safeUrl(v.video_url),poster=safeUrl(v.thumbnail_url),file=/\.(mp4|webm|mov)(\?|$)/i.test(url)||v.platform==="upload",isSaved=saved().has(v.id);return `<article class="video-card" data-id="${esc(v.id)}" data-user="${esc(v.user_id)}" data-url="${esc(url)}"><div class="video-media">${file&&url?`<video src="${esc(url)}" ${poster?`poster="${esc(poster)}"`:""} playsinline loop preload="metadata"></video>`:poster?`<img src="${esc(poster)}" alt="" loading="lazy">`:`<div class="video-placeholder"><b>LS8</b><span>${url?"Tocá para abrir":"Sin vista previa"}</span></div>`}</div><div class="shade"></div><div class="video-copy"><button class="creator-link" data-action="profile">@${esc(p.username||"usuario")}</button><p>${esc(v.title||"Nueva publicación")}</p><small>${esc((v.client_origin||v.platform||"LS8").toUpperCase())}</small></div><aside class="video-actions"><button data-action="profile" aria-label="Perfil"><span class="action-avatar">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(p.avatar_emoji||"○")}</span></button><button data-action="like" class="${likes.has(v.id)?"selected":""}" aria-label="Me gusta"><i>♥</i><span>${likes.has(v.id)?"Te gusta":"Like"}</span></button><button data-action="comments" aria-label="Comentarios"><i>●</i><span>Comentar</span></button><button data-action="share" aria-label="Compartir"><i>↗</i><span>Compartir</span></button><button data-action="save" class="${isSaved?"selected":""}" aria-label="Guardar"><i>▣</i><span>${isSaved?"Guardado":"Guardar"}</span></button></aside></article>`}

async function loadFeed(){const feed=$("#videoFeed");feed.innerHTML='<div class="state">Buscando señales…</div>';let q=sb.from("videos").select("id,user_id,title,video_url,thumbnail_url,platform,client_origin,created_at,profiles!videos_user_id_fkey(username,avatar_url,avatar_emoji)").order("created_at",{ascending:false}).limit(30);if(activeFeed==="siguiendo"){const f=await sb.from("follows").select("followed_id").eq("follower_id",currentUser.id),ids=(f.data||[]).map(x=>x.followed_id);if(!ids.length){feed.innerHTML='<div class="state">Todavía no seguís a ningún creador.</div>';return}q=q.in("user_id",ids)}const r=await q;if(r.error){feed.innerHTML='<button class="state error" id="retryFeed">No pudimos cargar el feed. Tocá para reintentar.</button>';$("#retryFeed").onclick=loadFeed;return}videos=r.data||[];let likes=new Set();if(videos.length){const l=await sb.from("video_likes").select("video_id").eq("user_id",currentUser.id).in("video_id",videos.map(v=>v.id));likes=new Set((l.data||[]).map(x=>x.video_id))}feed.innerHTML=videos.map((v,i)=>card(v,i,likes)).join("")||'<div class="state">Todavía no hay videos.</div>';bindCards();observe()}
function bindCards(){$$(".video-card").forEach(c=>c.onclick=e=>{const b=e.target.closest("[data-action]");if(b){e.stopPropagation();action(b.dataset.action,c,b);return}const v=c.querySelector("video");if(v)v.paused?v.play().catch(()=>{}):v.pause();else if(c.dataset.url)window.open(c.dataset.url,"_blank","noopener")})}
async function action(a,c,b){const id=c.dataset.id;if(a==="profile"){switchView("perfil");loadProfile(c.dataset.user);return}if(a==="comments")return openComments(id);if(a==="like"){if(b.classList.contains("selected"))return;loading(b,true,"···");const r=await sb.rpc("give_like",{p_video_id:id,p_user_id:currentUser.id});loading(b,false);if(r.error||!r.data?.ok)return toast(r.data?.error==="no_self_like"?"No podés dar like a tu video.":"No pudimos registrar el like.","error");b.classList.add("selected");b.querySelector("span").textContent="Te gusta";return toast(`Like registrado${r.data.points?` · +${r.data.points} pt`:""}`)}if(a==="save"){const ids=saved();ids.has(id)?ids.delete(id):ids.add(id);localStorage.setItem(savedKey,JSON.stringify([...ids]));b.classList.toggle("selected",ids.has(id));b.querySelector("span").textContent=ids.has(id)?"Guardado":"Guardar";return toast(ids.has(id)?"Publicación guardada":"Quitada de guardados")}if(a==="share"){const url=`${location.origin}${location.pathname}?video=${encodeURIComponent(id)}`;try{navigator.share?await navigator.share({title:"LiveScroll 8",url}):(await navigator.clipboard.writeText(url),toast("Enlace copiado"))}catch(e){if(e.name!=="AbortError")toast("No pudimos compartir.","error")}}}
function observe(){observer?.disconnect();observer=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target.querySelector("video");if(v)(e.isIntersecting&&e.intersectionRatio>.7?v.play():Promise.resolve(v.pause())).catch(()=>{})}),{threshold:[.2,.7]});$$(".video-card").forEach(c=>observer.observe(c))}

async function openComments(id){$("#modalWrap").innerHTML=`<div class="modal-overlay"><section class="comments-sheet"><header><h3>Comentarios</h3><button id="closeModal">×</button></header><div class="comments-list" id="commentsList"><div class="state">Cargando…</div></div><form id="commentForm" class="comment-form"><input id="commentInput" minlength="3" maxlength="500" placeholder="Escribí un comentario…" required><button class="primary">Enviar</button></form></section></div>`;$("#closeModal").onclick=closeModal;$(".modal-overlay").onclick=e=>{if(e.target.classList.contains("modal-overlay"))closeModal()};$("#commentForm").onsubmit=e=>submitComment(e,id);await loadComments(id)}
async function loadComments(id){const r=await sb.from("video_comments").select("id,content,created_at,client_origin,profiles!video_comments_user_id_fkey(username,avatar_url,avatar_emoji)").eq("video_id",id).order("created_at",{ascending:false}).limit(80),list=$("#commentsList");if(r.error){list.innerHTML='<div class="state error">No pudimos cargar los comentarios.</div>';return}list.innerHTML=(r.data||[]).map(c=>`<article class="comment"><span class="mini-avatar">${c.profiles?.avatar_url?`<img src="${esc(c.profiles.avatar_url)}" alt="">`:esc(c.profiles?.avatar_emoji||"○")}</span><div><b>@${esc(c.profiles?.username||"usuario")}</b><p>${esc(c.content)}</p><small>${new Date(c.created_at).toLocaleDateString("es-AR")} · ${esc((c.client_origin||"LS").toUpperCase())}</small></div></article>`).join("")||'<div class="state">Sé el primero en comentar.</div>'}
async function submitComment(e,id){e.preventDefault();const input=$("#commentInput"),btn=e.submitter,content=input.value.trim();loading(btn,true,"Enviando…");const r=await sb.rpc("add_comment",{p_video_id:id,p_user_id:currentUser.id,p_content:content});if(!r.error&&r.data?.ok)await sb.rpc("mark_latest_comment_origin",{p_video_id:id,p_origin:"ls8"});loading(btn,false);if(r.error||!r.data?.ok)return toast("No pudimos comentar.","error");input.value="";await loadComments(id);toast("Comentario publicado")}
function closeModal(){$("#modalWrap").innerHTML=""}

async function search(term){const target=$("#exploreResults"),value=term.trim();if(value.length<2){target.innerHTML='<div class="empty-card"><b>Buscá por nombre o título.</b><span>Escribí al menos dos letras.</span></div>';return}target.innerHTML='<div class="state">Buscando…</div>';const p=`%${value.replace(/[%_]/g,"")}%`,[a,b]=await Promise.all([sb.from("profiles").select("id,username,avatar_url,avatar_emoji,bio,is_creator,is_creator_verified").ilike("username",p).limit(15),sb.from("videos").select("id,title,thumbnail_url,platform,profiles!videos_user_id_fkey(username)").ilike("title",p).limit(15)]);const people=(a.data||[]).map(x=>`<button class="result-card" data-profile="${esc(x.id)}"><span class="result-avatar">${x.avatar_url?`<img src="${esc(x.avatar_url)}" alt="">`:esc(x.avatar_emoji||"○")}</span><span><small>${x.is_creator?"CREADOR":"USUARIO"}</small><b>@${esc(x.username||"usuario")}</b><em>${esc(x.bio||"Perfil de LiveScroll")}</em></span></button>`).join(""),posts=(b.data||[]).map(x=>`<div class="result-card"><span class="result-cover">${x.thumbnail_url?`<img src="${esc(x.thumbnail_url)}" alt="">`:"▶"}</span><span><small>${esc((x.platform||"VIDEO").toUpperCase())}</small><b>${esc(x.title||"Publicación")}</b><em>@${esc(x.profiles?.username||"usuario")}</em></span></div>`).join("");target.innerHTML=`${people?`<h3>Personas</h3>${people}`:""}${posts?`<h3>Publicaciones</h3>${posts}`:""}`||'<div class="state">No encontramos resultados.</div>';$$('[data-profile]').forEach(x=>x.onclick=()=>{switchView("perfil");loadProfile(x.dataset.profile)})}

async function publish(e){e.preventDefault();const f=e.currentTarget,btn=e.submitter,url=safeUrl(f.url.value),title=f.title.value.trim();if(!url)return toast("Ingresá un enlace válido.","error");loading(btn,true,"Publicando…");const r=await sb.from("videos").insert({user_id:currentUser.id,platform:f.platform.value,title,video_url:url,client_origin:"ls8"});loading(btn,false);if(r.error)return toast(`No pudimos publicar: ${r.error.message}`,"error");f.reset();toast("Publicado en LiveScroll 8");activeFeed="para-ti";switchView("inicio")}

async function loadAlerts(){const target=$("#alertsList");target.innerHTML='<div class="state">Cargando alertas…</div>';const r=await sb.from("notifications").select("*").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(60);if(r.error){target.innerHTML='<div class="state error">No pudimos cargar tus alertas.</div>';return}const icons={like:"♥",comment:"●",follow:"＋",live:"●",points:"◆"};target.innerHTML=(r.data||[]).map(n=>`<div class="alert-card ${n.read?"":"unread"}"><i>${icons[n.type]||"◇"}</i><span><b>${esc(n.message||"Nueva actividad")}</b><small>${new Date(n.created_at).toLocaleString("es-AR")}</small></span></div>`).join("")||'<div class="empty-card"><b>Todo tranquilo por acá.</b><span>Tu actividad aparecerá en este lugar.</span></div>';const ids=(r.data||[]).filter(n=>!n.read).map(n=>n.id);if(ids.length)await sb.from("notifications").update({read:true}).eq("user_id",currentUser.id).in("id",ids)}

async function loadProfile(id=currentUser.id){const target=$("#profileView");target.innerHTML='<div class="state">Cargando perfil…</div>';const p=await profile(id),own=id===currentUser.id,[posts,followers,following,state]=await Promise.all([sb.from("videos").select("id,title,thumbnail_url",{count:"exact"}).eq("user_id",id).order("created_at",{ascending:false}).limit(12),sb.from("follows").select("follower_id",{count:"exact",head:true}).eq("followed_id",id),sb.from("follows").select("followed_id",{count:"exact",head:true}).eq("follower_id",id),own?Promise.resolve({data:null}):sb.from("follows").select("follower_id").eq("follower_id",currentUser.id).eq("followed_id",id).maybeSingle()]);target.innerHTML=`<header class="profile-head"><div class="profile-avatar" id="profileAvatar"></div><div><small>${p.is_creator?"CREADOR":"USUARIO"}${p.is_creator_verified?" · VERIFICADO":""}</small><h2>@${esc(p.username||"usuario")}</h2><p>${esc(p.bio||"Este mundo todavía está tomando forma.")}</p></div></header><div class="profile-stats"><div><b>${posts.count||0}</b><span>Videos</span></div><div><b>${followers.count||0}</b><span>Seguidores</span></div><div><b>${following.count||0}</b><span>Siguiendo</span></div><div><b>${Number(p.points_balance||0)}</b><span>Puntos</span></div></div>${own?'<button class="logout" id="logoutBtn">Cerrar sesión</button>':`<button class="primary follow-button ${state.data?"following":""}" id="followBtn">${state.data?"Siguiendo":"Seguir"}</button>`}<section class="profile-posts"><h3>Publicaciones</h3><div>${(posts.data||[]).map(v=>`<div>${v.thumbnail_url?`<img src="${esc(v.thumbnail_url)}" alt="">`:"▶"}<span>${esc(v.title||"Publicación")}</span></div>`).join("")||'<p>Todavía no publicó videos.</p>'}</div></section>`;avatar($("#profileAvatar"),p);if(own)$("#logoutBtn").onclick=()=>sb.auth.signOut();else $("#followBtn").onclick=async e=>{const btn=e.currentTarget,r=await sb.rpc("toggle_follow",{p_follower_id:currentUser.id,p_followed_id:id});if(r.error||!r.data?.ok)return toast("No pudimos actualizar el seguimiento.","error");btn.classList.toggle("following",r.data.following);btn.textContent=r.data.following?"Siguiendo":"Seguir"}}

async function switchView(view){activeView=view;observer?.disconnect();$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===view));$$('.view').forEach(s=>s.classList.toggle("active",s.id===`view-${view}`));$("#feedTabs").classList.toggle("hidden",view!=="inicio");if(view==="inicio")loadFeed();if(view==="perfil")loadProfile();if(view==="alertas")loadAlerts();if(view==="explorar")setTimeout(()=>$("#searchInput").focus(),80)}
async function boot(){if(!await identity())return showApp(false);await switchView(activeView)}

$$('[data-auth-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.authMode;$$('[data-auth-mode]').forEach(x=>x.classList.toggle("active",x===b));$("#authSubmit").textContent=authMode==="login"?"ENTRAR A LS8":"CREAR MI CUENTA";$("#authStatus").textContent=""});
$("#authForm").onsubmit=async e=>{e.preventDefault();const btn=$("#authSubmit"),email=$("#email").value.trim(),password=$("#password").value;loading(btn,true,"CONECTANDO…");const r=authMode==="login"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});loading(btn,false);if(r.error)return $("#authStatus").textContent=authError(r.error);if(authMode==="signup"&&!r.data.session)return $("#authStatus").textContent="Cuenta creada. Revisá tu correo para confirmarla.";showApp(true)};
$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-feed]').forEach(b=>b.onclick=()=>{activeFeed=b.dataset.feed;$$('[data-feed]').forEach(x=>x.classList.toggle("active",x===b));loadFeed()});
$("#topAvatar").onclick=()=>switchView("perfil");$("#searchInput").oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>search(e.target.value),280)};$("#publishForm").onsubmit=publish;
sb.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT"){currentUser=null;showApp(false)}else if(event==="SIGNED_IN"&&session&&!currentUser)showApp(true)});
sb.auth.getSession().then(r=>showApp(Boolean(r.data.session))).catch(()=>showApp(false));
