const SUPABASE_URL="https://lxpjqvlphvjyygifedeb.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4cGpxdmxwaHZqeXlnaWZlZGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0MTMyMTMsImV4cCI6MjA5ODk4OTIxM30.9ovZlNQ-XKdSszZuMYb6PzRnXtX5eejuzBeqpKgkVnk";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const signal=document.querySelector(".signal-stage"),access=document.querySelector("#accessStage"),appStage=document.querySelector("#appStage"),statusEl=document.querySelector("#status"),form=document.querySelector("#authForm");
let mode="login";
function showAccess(open){signal.classList.toggle("hidden",open);access.classList.toggle("open",open);access.setAttribute("aria-hidden",String(!open));if(open)setTimeout(()=>document.querySelector("#email").focus(),400)}
function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function showApp(open){signal.classList.add("hidden");access.classList.remove("open");access.setAttribute("aria-hidden","true");appStage.classList.toggle("open",open);appStage.setAttribute("aria-hidden",String(!open));if(open)(window.ls8Start||loadWorld)()}
function mediaUrl(video){return video.thumbnail_url||((video.platform==="upload"||/\.(mp4|webm)(\?|$)/i.test(video.video_url||""))?video.video_url:"")}
async function loadWorld(){
  const [{data:{user}},{data:videos,error}]=await Promise.all([sb.auth.getUser(),sb.from("videos").select("id,title,video_url,thumbnail_url,platform,client_origin,created_at,profiles!videos_user_id_fkey(username,avatar_url,avatar_emoji)").order("created_at",{ascending:false}).limit(12)]);
  if(user){const {data:profile}=await sb.from("profiles").select("username,avatar_url,avatar_emoji").eq("id",user.id).maybeSingle();const name=profile?.username||user.email?.split("@")[0]||"creador";document.querySelector("#worldGreeting").textContent=`Buenas, ${name}.`;const avatar=document.querySelector("#worldAvatar");if(profile?.avatar_url)avatar.innerHTML=`<img src="${escapeHtml(profile.avatar_url)}" alt="" style="width:100%;height:100%;object-fit:cover;border-radius:50%">`;else avatar.textContent=profile?.avatar_emoji||"8"}
  const feed=document.querySelector("#signalFeed");if(error){feed.innerHTML=`<div class="feed-empty">No pudimos encontrar las señales. Volvé a intentar.</div>`;return}document.querySelector("#signalCount").textContent=String(videos?.length||0).padStart(2,"0");
  feed.innerHTML=(videos||[]).map((v,i)=>{const media=mediaUrl(v),author=v.profiles?.username||"usuario";return `<article class="signal-card" data-url="${escapeHtml(v.video_url||"")}"><div class="signal-media">${media?`<img src="${escapeHtml(media)}" alt="" loading="lazy">`:`<div style="height:100%;display:grid;place-items:center;color:#43e8ff;font-size:42px">◇</div>`}<span class="signal-index">${String(i+1).padStart(2,"0")}</span></div><div class="signal-card-copy"><strong>${escapeHtml(v.title||"Señal sin título")}</strong><span>@${escapeHtml(author)}</span></div><i class="signal-origin">${escapeHtml((v.client_origin||v.platform||"LS").toUpperCase())}</i></article>`}).join("")||`<div class="feed-empty">Todavía no hay señales para mostrar.</div>`;
  feed.querySelectorAll(".signal-card").forEach(card=>card.onclick=()=>{const url=card.dataset.url;if(url)window.open(url,"_blank","noopener")});
}
document.querySelector("#discoverBtn").onclick=()=>showAccess(true);document.querySelector("#backBtn").onclick=()=>showAccess(false);
document.querySelectorAll("[data-mode]").forEach(btn=>btn.onclick=()=>{mode=btn.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("active",x===btn));document.querySelector("#accessTitle").textContent=mode==="login"?"Tu señal sigue activa.":"Creá tu primera señal.";document.querySelector("#accessText").textContent=mode==="login"?"Ingresá con la misma cuenta de LiveScroll.":"Una cuenta para todas las generaciones de LiveScroll.";document.querySelector("#submitText").textContent=mode==="login"?"ENTRAR A LS8":"CREAR MI CUENTA";statusEl.textContent=""});
form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector("button"),email=document.querySelector("#email").value.trim(),password=document.querySelector("#password").value;button.disabled=true;statusEl.className="status";statusEl.textContent="Conectando tu señal…";const result=mode==="login"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});button.disabled=false;if(result.error){statusEl.textContent=result.error.message;return}if(mode==="login")showApp(true);else{statusEl.classList.add("ok");statusEl.textContent="Cuenta creada. Revisá tu correo si se solicita confirmación."}};
document.querySelector("#refreshBtn").onclick=loadWorld;document.querySelector("#exitBtn").onclick=async()=>{await sb.auth.signOut();appStage.classList.remove("open");showAccess(true);statusEl.textContent="Sesión cerrada."};
document.querySelectorAll("[data-view]").forEach(btn=>btn.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===btn));if(btn.dataset.view!=="inicio")document.querySelector("#signalFeed").innerHTML=`<div class="feed-empty">${btn.dataset.view==="perfil"?"Tu mundo personal será la próxima pantalla.":"El nuevo explorador de mundos está en preparación."}</div>`;else loadWorld()});
sb.auth.getSession().then(({data})=>{if(data.session)showApp(true)});
