const SUPABASE_URL="https://lxpjqvlphvjyygifedeb.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4cGpxdmxwaHZqeXlnaWZlZGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0MTMyMTMsImV4cCI6MjA5ODk4OTIxM30.9ovZlNQ-XKdSszZuMYb6PzRnXtX5eejuzBeqpKgkVnk";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
let authMode="login",activeFeed="para-ti",activeView="inicio",currentUser=null,currentProfile={},videos=[],observer,paginationObserver,searchTimer,liveTimer=null,bootPromise=null,viewToken=0;
const savedKey="livescroll8_saved_videos";
const MEDIA_API="https://livescroll-media-api.ezequielmarcosrodriguez.workers.dev",FEED_PAGE=20,PROFILE_PAGE=24,MAX_FILE_MB=50;
let feedOffset=0,feedDone=false,feedBusy=false,profilePostOffset=0,profilePostDone=false,profilePostBusy=false,profileOwnerId=null,uploadPreviewUrl="";

function safeUrl(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:""}catch{return""}}
function toast(message,type="ok"){$("#toast").textContent=message;$("#toast").className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$("#toast").className="toast",2600)}
function loading(btn,on,text="Cargando…"){btn.disabled=on;btn.dataset.text||=btn.textContent;btn.textContent=on?text:btn.dataset.text}
function saved(){try{return new Set(JSON.parse(localStorage.getItem(savedKey)||"[]"))}catch{return new Set()}}
function avatar(el,p){if(!el)return;el.innerHTML=p?.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(p?.avatar_emoji||"8")}
function authError(e){const m=String(e?.message||e);if(/invalid login/i.test(m))return"Correo o contraseña incorrectos.";if(/email not confirmed/i.test(m))return"Primero confirmá tu correo.";if(/network|fetch/i.test(m))return"No pudimos conectar. Revisá tu internet.";return m}
function showApp(open){$("#authScreen").classList.toggle("hidden",open);$("#mainApp").classList.toggle("open",open);$("#mainApp").setAttribute("aria-hidden",!open);if(open)boot()}

async function profile(id){let r=await sb.from("profiles").select("id,username,avatar_url,avatar_emoji,bio,points_balance,is_creator,is_creator_verified,social_instagram,social_kick,social_twitch,social_youtube,social_tiktok").eq("id",id).maybeSingle();if(r.error)r=await sb.from("profiles").select("id,username,avatar_url,avatar_emoji,bio,is_creator").eq("id",id).maybeSingle();return r.data||{}}
async function identity(){const r=await sb.auth.getUser();currentUser=r.data.user;if(!currentUser)return false;currentProfile=await profile(currentUser.id);avatar($("#topAvatar"),currentProfile);return true}

function card(v,i,likes){const p=v.profiles||{},url=safeUrl(v.video_url),poster=safeUrl(v.thumbnail_url),file=/\.(mp4|webm|mov)(\?|$)/i.test(url)||v.platform==="upload",isSaved=saved().has(v.id);return `<article class="video-card" data-id="${esc(v.id)}" data-user="${esc(v.user_id)}" data-url="${esc(url)}"><div class="video-media">${file&&url?`<video src="${esc(url)}" ${poster?`poster="${esc(poster)}"`:""} playsinline loop preload="metadata"></video>`:poster?`<img src="${esc(poster)}" alt="" loading="lazy">`:`<div class="video-placeholder"><b>LS8</b><span>${url?"Tocá para abrir":"Sin vista previa"}</span></div>`}</div><div class="shade"></div><div class="video-copy"><button class="creator-link" data-action="profile">@${esc(p.username||"usuario")}</button><p>${esc(v.title||"Nueva publicación")}</p><small>${esc((v.client_origin||v.platform||"LS8").toUpperCase())}</small></div><aside class="video-actions"><button data-action="profile" aria-label="Perfil"><span class="action-avatar">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(p.avatar_emoji||"○")}</span></button><button data-action="like" class="${likes.has(v.id)?"selected":""}" aria-label="Me gusta"><i>♥</i><span>${likes.has(v.id)?"Te gusta":"Like"}</span></button><button data-action="comments" aria-label="Comentarios"><i>●</i><span>Comentar</span></button><button data-action="share" aria-label="Compartir"><i>↗</i><span>Compartir</span></button><button data-action="save" class="${isSaved?"selected":""}" aria-label="Guardar"><i>▣</i><span>${isSaved?"Guardado":"Guardar"}</span></button></aside></article>`}

async function loadFeed(reset=true){if(feedBusy)return;feedBusy=true;const feed=$("#videoFeed");if(reset){feedOffset=0;feedDone=false;videos=[];paginationObserver?.disconnect();feed.innerHTML='<div class="state">Buscando señales…</div>'}if(feedDone){feedBusy=false;return}let q=sb.from("videos").select("id,user_id,title,video_url,thumbnail_url,platform,client_origin,created_at,profiles!videos_user_id_fkey(username,avatar_url,avatar_emoji)").order("created_at",{ascending:false}).range(feedOffset,feedOffset+FEED_PAGE-1);if(activeFeed==="siguiendo"){const f=await sb.from("follows").select("followed_id").eq("follower_id",currentUser.id),ids=(f.data||[]).map(x=>x.followed_id);if(!ids.length){feed.innerHTML='<div class="state">Todavía no seguís a ningún creador.</div>';feedBusy=false;return}q=q.in("user_id",ids)}const r=await q;if(r.error){feed.innerHTML='<button class="state error" id="retryFeed">No pudimos cargar el feed. Tocá para reintentar.</button>';$("#retryFeed").onclick=()=>loadFeed(true);feedBusy=false;return}const page=r.data||[];let likes=new Set();if(page.length){const l=await sb.from("video_likes").select("video_id").eq("user_id",currentUser.id).in("video_id",page.map(v=>v.id));likes=new Set((l.data||[]).map(x=>x.video_id))}if(reset)feed.innerHTML="";const start=videos.length;videos.push(...page);feed.insertAdjacentHTML("beforeend",page.map((v,i)=>card(v,start+i,likes)).join(""));feedOffset+=page.length;feedDone=page.length<FEED_PAGE;$("#feedMore")?.remove();if(!feedDone)feed.insertAdjacentHTML("beforeend",'<button class="load-more" id="feedMore" type="button">CARGANDO MÁS SEÑALES <b>↓</b></button>');else if(videos.length)feed.insertAdjacentHTML("beforeend",'<div class="feed-complete">Llegaste al comienzo de LiveScroll.</div>');if(!videos.length)feed.innerHTML='<div class="state">Todavía no hay videos.</div>';bindCards();observe();const more=$("#feedMore");if(more){more.onclick=()=>loadFeed(false);paginationObserver=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)loadFeed(false)},{root:feed,rootMargin:"500px"});paginationObserver.observe(more)}feedBusy=false}
function bindCards(){$$(".video-card").forEach(c=>c.onclick=e=>{const b=e.target.closest("[data-action]");if(b){e.stopPropagation();action(b.dataset.action,c,b);return}const v=c.querySelector("video");if(v)v.paused?v.play().catch(()=>{}):v.pause();else if(c.dataset.url)window.open(c.dataset.url,"_blank","noopener")})}
async function action(a,c,b){const id=c.dataset.id;if(a==="profile"){switchView("perfil");loadProfile(c.dataset.user);return}if(a==="comments")return openComments(id);if(a==="like"){if(b.classList.contains("selected"))return;loading(b,true,"···");const r=await sb.rpc("give_like",{p_video_id:id,p_user_id:currentUser.id});loading(b,false);if(r.error||!r.data?.ok)return toast(r.data?.error==="no_self_like"?"No podés dar like a tu video.":"No pudimos registrar el like.","error");b.classList.add("selected");b.querySelector("span").textContent="Te gusta";return toast(`Like registrado${r.data.points?` · +${r.data.points} pt`:""}`)}if(a==="save"){const ids=saved();ids.has(id)?ids.delete(id):ids.add(id);localStorage.setItem(savedKey,JSON.stringify([...ids]));b.classList.toggle("selected",ids.has(id));b.querySelector("span").textContent=ids.has(id)?"Guardado":"Guardar";return toast(ids.has(id)?"Publicación guardada":"Quitada de guardados")}if(a==="share"){const url=`${location.origin}${location.pathname}?video=${encodeURIComponent(id)}`;try{navigator.share?await navigator.share({title:"LiveScroll 8",url}):(await navigator.clipboard.writeText(url),toast("Enlace copiado"))}catch(e){if(e.name!=="AbortError")toast("No pudimos compartir.","error")}}}
function observe(){observer?.disconnect();observer=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target.querySelector("video");if(v)(e.isIntersecting&&e.intersectionRatio>.7?v.play():Promise.resolve(v.pause())).catch(()=>{})}),{threshold:[.2,.7]});$$(".video-card").forEach(c=>observer.observe(c))}

async function openComments(id){$("#modalWrap").innerHTML=`<div class="modal-overlay"><section class="comments-sheet"><header><h3>Comentarios</h3><button id="closeModal">×</button></header><div class="comments-list" id="commentsList"><div class="state">Cargando…</div></div><form id="commentForm" class="comment-form"><input id="commentInput" minlength="3" maxlength="500" placeholder="Escribí un comentario…" required><button class="primary">Enviar</button></form></section></div>`;$("#closeModal").onclick=closeModal;$(".modal-overlay").onclick=e=>{if(e.target.classList.contains("modal-overlay"))closeModal()};$("#commentForm").onsubmit=e=>submitComment(e,id);await loadComments(id)}
async function loadComments(id){const r=await sb.from("video_comments").select("id,content,created_at,client_origin,profiles!video_comments_user_id_fkey(username,avatar_url,avatar_emoji)").eq("video_id",id).order("created_at",{ascending:false}).limit(80),list=$("#commentsList");if(r.error){list.innerHTML='<div class="state error">No pudimos cargar los comentarios.</div>';return}list.innerHTML=(r.data||[]).map(c=>`<article class="comment"><span class="mini-avatar">${c.profiles?.avatar_url?`<img src="${esc(c.profiles.avatar_url)}" alt="">`:esc(c.profiles?.avatar_emoji||"○")}</span><div><b>@${esc(c.profiles?.username||"usuario")}</b><p>${esc(c.content)}</p><small>${new Date(c.created_at).toLocaleDateString("es-AR")} · ${esc((c.client_origin||"LS").toUpperCase())}</small></div></article>`).join("")||'<div class="state">Sé el primero en comentar.</div>'}
async function submitComment(e,id){e.preventDefault();const input=$("#commentInput"),btn=e.submitter,content=input.value.trim();loading(btn,true,"Enviando…");const r=await sb.rpc("add_comment",{p_video_id:id,p_user_id:currentUser.id,p_content:content});if(!r.error&&r.data?.ok)await sb.rpc("mark_latest_comment_origin",{p_video_id:id,p_origin:"ls8"});loading(btn,false);if(r.error||!r.data?.ok)return toast("No pudimos comentar.","error");input.value="";await loadComments(id);toast("Comentario publicado")}
function closeModal(){$("#modalWrap").innerHTML=""}

async function search(term){const target=$("#exploreResults"),value=term.trim();if(value.length<2){target.innerHTML='<div class="empty-card"><b>Buscá por nombre o título.</b><span>Escribí al menos dos letras.</span></div>';return}target.innerHTML='<div class="state">Buscando…</div>';const p=`%${value.replace(/[%_]/g,"")}%`,[a,b]=await Promise.all([sb.from("profiles").select("id,username,avatar_url,avatar_emoji,bio,is_creator,is_creator_verified").ilike("username",p).limit(15),sb.from("videos").select("id,title,thumbnail_url,platform,profiles!videos_user_id_fkey(username)").ilike("title",p).limit(15)]);const people=(a.data||[]).map(x=>`<button class="result-card" data-profile="${esc(x.id)}"><span class="result-avatar">${x.avatar_url?`<img src="${esc(x.avatar_url)}" alt="">`:esc(x.avatar_emoji||"○")}</span><span><small>${x.is_creator?"CREADOR":"USUARIO"}</small><b>@${esc(x.username||"usuario")}</b><em>${esc(x.bio||"Perfil de LiveScroll")}</em></span></button>`).join(""),posts=(b.data||[]).map(x=>`<div class="result-card"><span class="result-cover">${x.thumbnail_url?`<img src="${esc(x.thumbnail_url)}" alt="">`:"▶"}</span><span><small>${esc((x.platform||"VIDEO").toUpperCase())}</small><b>${esc(x.title||"Publicación")}</b><em>@${esc(x.profiles?.username||"usuario")}</em></span></div>`).join("");target.innerHTML=`${people?`<h3>Personas</h3>${people}`:""}${posts?`<h3>Publicaciones</h3>${posts}`:""}`||'<div class="state">No encontramos resultados.</div>';$$('[data-profile]').forEach(x=>x.onclick=()=>{switchView("perfil");loadProfile(x.dataset.profile)})}

async function publish(e){e.preventDefault();const f=e.currentTarget,btn=e.submitter,url=safeUrl(f.url.value),title=f.title.value.trim();if(!url)return toast("Ingresá un enlace válido.","error");loading(btn,true,"Publicando…");const r=await sb.from("videos").insert({user_id:currentUser.id,platform:f.platform.value,title,video_url:url,client_origin:"ls8"});loading(btn,false);if(r.error)return toast(`No pudimos publicar: ${r.error.message}`,"error");f.reset();toast("Publicado en LiveScroll 8");activeFeed="para-ti";switchView("inicio")}

async function loadAlerts(){const target=$("#alertsList");target.innerHTML='<div class="state">Cargando alertas…</div>';const r=await sb.from("notifications").select("*").eq("user_id",currentUser.id).order("created_at",{ascending:false}).limit(60);if(r.error){target.innerHTML='<div class="state error">No pudimos cargar tus alertas.</div>';return}const icons={like:"♥",comment:"●",follow:"＋",live:"●",points:"◆"};target.innerHTML=(r.data||[]).map(n=>`<div class="alert-card ${n.read?"":"unread"}"><i>${icons[n.type]||"◇"}</i><span><b>${esc(n.message||"Nueva actividad")}</b><small>${new Date(n.created_at).toLocaleString("es-AR")}</small></span></div>`).join("")||'<div class="empty-card"><b>Todo tranquilo por acá.</b><span>Tu actividad aparecerá en este lugar.</span></div>';const ids=(r.data||[]).filter(n=>!n.read).map(n=>n.id);if(ids.length)await sb.from("notifications").update({read:true}).eq("user_id",currentUser.id).in("id",ids)}

const livePlatforms={kick:{label:"KICK",color:"#53fc18",base:"https://kick.com/"},twitch:{label:"TWITCH",color:"#a970ff",base:"https://twitch.tv/"},youtube:{label:"YOUTUBE",color:"#ff3040",base:"https://youtube.com/"},tiktok:{label:"TIKTOK",color:"#25f4ee",base:"https://tiktok.com/"}};
function liveUrl(p,name){const raw=String(p[`social_${name}`]||"").trim();if(!raw)return"";const direct=safeUrl(raw);if(direct)return direct;const handle=raw.replace(/^@/,"").replace(/^\/+|\/+$/g,"");if(!handle)return"";if(name==="tiktok")return`${livePlatforms[name].base}@${handle}`;if(name==="youtube"&&raw.startsWith("@"))return`${livePlatforms[name].base}@${handle}`;return livePlatforms[name].base+handle}
function activePlatforms(p){return Object.keys(livePlatforms).filter(name=>Boolean(p[`${name}_is_live`]||p.live_platform===name))}
function liveCard(p,names){const colors=names.map(name=>livePlatforms[name].color);return `<article class="live-card" style="--live-a:${colors[0]};--live-b:${colors[1]||colors[0]}"><div class="live-card-glow"></div><header><span class="live-avatar">${p.avatar_url?`<img src="${esc(p.avatar_url)}" alt="">`:esc(p.avatar_emoji||"●")}</span><span><small><i></i> TRANSMITIENDO AHORA</small><b>@${esc(p.username||"creador")}</b></span></header><p>${esc(p.bio||"Una señal está ocurriendo en este momento.")}</p><div class="live-platforms">${names.map(name=>`<span style="--platform:${livePlatforms[name].color}">${livePlatforms[name].label}</span>`).join("")}</div><div class="live-actions">${names.map(name=>{const url=liveUrl(p,name);return url?`<a href="${esc(url)}" target="_blank" rel="noopener">VER EN ${livePlatforms[name].label}<b>↗</b></a>`:""}).join("")||'<button type="button" disabled>ENLACE NO DISPONIBLE</button>'}</div></article>`}
async function loadLives(force=false){const token=++viewToken,grid=$("#liveGrid"),summary=$("#liveSummary");if(!grid)return;grid.innerHTML='<div class="state">Localizando directos…</div>';summary.innerHTML='<i></i><span>Sincronizando señales activas…</span>';let r=await sb.from("profiles").select("id,username,avatar_url,avatar_emoji,bio,is_live,live_platform,kick_is_live,twitch_is_live,youtube_is_live,tiktok_is_live,social_kick,social_twitch,social_youtube,social_tiktok").limit(100);if(r.error)r=await sb.from("profiles").select("id,username,avatar_url,avatar_emoji,bio,is_live,live_platform,social_kick,social_twitch,social_youtube,social_tiktok").eq("is_live",true).limit(100);if(token!==viewToken||activeView!=="directos")return;if(r.error){grid.innerHTML='<button class="state error" id="retryLives">No pudimos consultar los directos. Tocá para reintentar.</button>';$("#retryLives").onclick=()=>loadLives(true);summary.innerHTML='<i class="offline"></i><span>Centro en vivo sin conexión</span>';return}const lives=(r.data||[]).map(p=>({p,names:activePlatforms(p)})).filter(x=>x.p.is_live||x.names.length).map(x=>({p:x.p,names:x.names.length?x.names:[x.p.live_platform].filter(Boolean)})).filter(x=>x.names.length);summary.innerHTML=`<i class="${lives.length?"":"offline"}"></i><span>${lives.length?`${lives.length} ${lives.length===1?"creador está":"creadores están"} transmitiendo ahora`:"No hay transmisiones activas en este momento"}</span>`;grid.innerHTML=lives.map(x=>liveCard(x.p,x.names)).join("")||'<div class="live-empty"><b>El pulso está en calma.</b><span>Cuando alguien inicie directo aparecerá acá automáticamente.</span></div>';if(force)toast("Directos actualizados")}
function stopLiveRefresh(){if(liveTimer)clearInterval(liveTimer);liveTimer=null}
function startLiveRefresh(){stopLiveRefresh();liveTimer=setInterval(()=>{if(activeView==="directos"&&!document.hidden)loadLives()},45000)}

async function loadProfile(id=currentUser.id){const target=$("#profileView");target.innerHTML='<div class="state">Cargando perfil…</div>';profileOwnerId=id;profilePostOffset=0;profilePostDone=false;const p=await profile(id),own=id===currentUser.id,[postsCount,followers,following,state]=await Promise.all([sb.from("videos").select("id",{count:"exact",head:true}).eq("user_id",id),sb.from("follows").select("follower_id",{count:"exact",head:true}).eq("followed_id",id),sb.from("follows").select("followed_id",{count:"exact",head:true}).eq("follower_id",id),own?Promise.resolve({data:null}):sb.from("follows").select("follower_id").eq("follower_id",currentUser.id).eq("followed_id",id).maybeSingle()]);target.innerHTML=`<header class="profile-head"><div class="profile-avatar" id="profileAvatar"></div><div><small>${p.is_creator?"CREADOR":"USUARIO"}${p.is_creator_verified?" · VERIFICADO":""}</small><h2>@${esc(p.username||"usuario")}</h2><p>${esc(p.bio||"Este mundo todavía está tomando forma.")}</p></div></header><div class="profile-stats"><div><b>${postsCount.count||0}</b><span>Videos</span></div><div><b>${followers.count||0}</b><span>Seguidores</span></div><div><b>${following.count||0}</b><span>Siguiendo</span></div><div><b>${Number(p.points_balance||0)}</b><span>Puntos</span></div></div><div class="profile-buttons">${own?'<button class="profile-edit" id="editProfileBtn">Editar perfil</button><button class="logout" id="logoutBtn">Cerrar sesión</button>':`<button class="primary follow-button ${state.data?"following":""}" id="followBtn">${state.data?"Siguiendo":"Seguir"}</button>`}</div><section class="profile-posts"><h3>Publicaciones</h3><div id="profilePostsGrid"></div><button class="load-more hidden" id="profileMore" type="button">CARGAR MÁS VIDEOS <b>↓</b></button></section>`;avatar($("#profileAvatar"),p);if(own){$("#logoutBtn").onclick=()=>sb.auth.signOut();$("#editProfileBtn").onclick=()=>openProfileEditor(p)}else $("#followBtn").onclick=async e=>{const btn=e.currentTarget,r=await sb.rpc("toggle_follow",{p_follower_id:currentUser.id,p_followed_id:id});if(r.error||!r.data?.ok)return toast("No pudimos actualizar el seguimiento.","error");btn.classList.toggle("following",r.data.following);btn.textContent=r.data.following?"Siguiendo":"Seguir"};$("#profileMore").onclick=loadMoreProfilePosts;await loadMoreProfilePosts()}

async function loadMoreProfilePosts(){if(profilePostBusy||profilePostDone||!profileOwnerId)return;profilePostBusy=true;const owner=profileOwnerId,r=await sb.from("videos").select("id,title,thumbnail_url,video_url,platform").eq("user_id",owner).order("created_at",{ascending:false}).range(profilePostOffset,profilePostOffset+PROFILE_PAGE-1);if(owner!==profileOwnerId){profilePostBusy=false;return}if(r.error){toast("No pudimos cargar los videos del perfil.","error");profilePostBusy=false;return}const page=r.data||[],grid=$("#profilePostsGrid");grid.insertAdjacentHTML("beforeend",page.map(v=>`<button class="profile-video" data-profile-video="${esc(v.id)}" data-url="${esc(safeUrl(v.video_url))}">${v.thumbnail_url?`<img src="${esc(v.thumbnail_url)}" alt="">`:"▶"}<span>${esc(v.title||"Publicación")}</span></button>`).join(""));profilePostOffset+=page.length;profilePostDone=page.length<PROFILE_PAGE;$("#profileMore").classList.toggle("hidden",profilePostDone);if(!profilePostOffset)grid.innerHTML='<p>Todavía no publicó videos.</p>';$$('[data-profile-video]').forEach(button=>button.onclick=()=>{if(button.dataset.url)window.open(button.dataset.url,"_blank","noopener")});profilePostBusy=false}

async function uploadMedia(file){if(!file?.size)throw new Error("Elegí un video.");if(file.size>MAX_FILE_MB*1024*1024)throw new Error(`El video supera los ${MAX_FILE_MB} MB.`);const session=await sb.auth.getSession(),token=session.data.session?.access_token;if(!token)throw new Error("Tu sesión venció. Volvé a iniciar sesión.");const response=await fetch(`${MEDIA_API}/upload`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":file.type||"application/octet-stream"},body:file});let result={};try{result=await response.json()}catch{}if(!response.ok||!result.ok||!result.url)throw new Error(result.error==="archivo_demasiado_grande"?`El video supera los ${result.max_mb||MAX_FILE_MB} MB.`:"No pudimos guardar el archivo en el servidor.");return result.url}
function previewUploadFile(){const file=$("#videoFile").files[0],preview=$("#uploadPreview");if(uploadPreviewUrl)URL.revokeObjectURL(uploadPreviewUrl);uploadPreviewUrl="";preview.classList.add("hidden");if(!file)return;$("#fileLabel").textContent=`${file.name} · ${(file.size/1048576).toFixed(1)} MB`;if(file.size>MAX_FILE_MB*1048576)return toast(`El video supera los ${MAX_FILE_MB} MB.`,"error");uploadPreviewUrl=URL.createObjectURL(file);preview.src=uploadPreviewUrl;preview.classList.remove("hidden")}
async function publishFile(e){e.preventDefault();const form=e.currentTarget,button=e.submitter,file=form.file.files[0],title=form.title.value.trim(),progress=$("#uploadProgress");loading(button,true,"SUBIENDO…");progress.classList.remove("hidden");try{const url=await uploadMedia(file),r=await sb.from("videos").insert({user_id:currentUser.id,platform:"upload",title,video_url:url,client_origin:"ls8"});if(r.error)throw r.error;form.reset();if(uploadPreviewUrl)URL.revokeObjectURL(uploadPreviewUrl);uploadPreviewUrl="";$("#uploadPreview").classList.add("hidden");$("#fileLabel").textContent="Elegir video · máximo 50 MB";toast("Video publicado en LS8");switchView("inicio")}catch(error){toast(error.message||"No pudimos publicar el video.","error")}finally{loading(button,false);progress.classList.add("hidden")}}

function openProfileEditor(p){const creator=p.is_creator===true;$("#modalWrap").innerHTML=`<div class="modal-overlay"><form class="profile-editor" id="profileEditor"><header><div><small>TU IDENTIDAD LS8</small><h3>Editar perfil</h3></div><button type="button" id="closeEditor">×</button></header><label>Nombre de usuario<input name="username" minlength="3" maxlength="28" value="${esc(p.username||"")}" required></label><label>Biografía<textarea name="bio" maxlength="120" placeholder="Contá algo sobre vos">${esc(p.bio||"")}</textarea></label><label>Avatar con emoji<input name="emoji" maxlength="4" value="${esc(p.avatar_emoji||"🎬")}"></label><label>Instagram<input name="instagram" type="url" value="${esc(p.social_instagram||"")}" placeholder="https://instagram.com/…"></label>${creator?`<div class="editor-socials"><label>Kick<input name="kick" type="url" value="${esc(p.social_kick||"")}"></label><label>Twitch<input name="twitch" type="url" value="${esc(p.social_twitch||"")}"></label><label>YouTube<input name="youtube" type="url" value="${esc(p.social_youtube||"")}"></label><label>TikTok<input name="tiktok" type="url" value="${esc(p.social_tiktok||"")}"></label></div>`:'<div class="creator-lock"><b>Redes de creador bloqueadas</b><span>Kick, Twitch, YouTube y TikTok se habilitan con el acceso Creador.</span></div>'}<button class="primary" type="submit">GUARDAR CAMBIOS</button></form></div>`;$("#closeEditor").onclick=closeModal;$("#profileEditor").onsubmit=e=>saveProfile(e,p,creator)}
async function saveProfile(e,p,creator){e.preventDefault();const form=e.currentTarget,button=e.submitter,username=form.username.value.trim(),bio=form.bio.value.trim(),emoji=form.emoji.value.trim()||"🎬";loading(button,true,"GUARDANDO…");if(username!==p.username){const changed=await sb.rpc("update_username",{p_user_id:currentUser.id,p_new_username:username});if(changed.error||!changed.data?.ok){loading(button,false);return toast(changed.data?.error==="nombre_ocupado"?"Ese nombre ya está en uso.":"Revisá el nombre de usuario.","error")}}const payload={bio,avatar_emoji:emoji,social_instagram:form.instagram.value.trim()||null};if(creator)Object.assign(payload,{social_kick:form.kick.value.trim()||null,social_twitch:form.twitch.value.trim()||null,social_youtube:form.youtube.value.trim()||null,social_tiktok:form.tiktok.value.trim()||null});const updated=await sb.from("profiles").update(payload).eq("id",currentUser.id);loading(button,false);if(updated.error)return toast("No pudimos guardar el perfil.","error");currentProfile={...currentProfile,...payload,username};closeModal();toast("Perfil actualizado");loadProfile(currentUser.id);avatar($("#topAvatar"),currentProfile)}

async function switchView(view){activeView=view;viewToken++;observer?.disconnect();if(view!=="directos")stopLiveRefresh();$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===view));$$('.view').forEach(s=>s.classList.toggle("active",s.id===`view-${view}`));$("#feedTabs").classList.toggle("hidden",view!=="inicio");if(view==="inicio")loadFeed();if(view==="perfil")loadProfile();if(view==="alertas")loadAlerts();if(view==="directos"){loadLives();startLiveRefresh()}if(view==="explorar")setTimeout(()=>$("#searchInput").focus(),80)}
async function boot(){if(bootPromise)return bootPromise;bootPromise=(async()=>{try{if(!await identity())return showApp(false);await switchView(activeView)}catch(error){console.error("LS8 no pudo iniciar",error);toast("No pudimos iniciar LS8. Reintentando…","error");setTimeout(()=>{bootPromise=null;boot()},1800)}finally{bootPromise=null}})();return bootPromise}

$$('[data-auth-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.authMode;$$('[data-auth-mode]').forEach(x=>x.classList.toggle("active",x===b));$("#authSubmit").textContent=authMode==="login"?"ENTRAR A LS8":"CREAR MI CUENTA";$("#authStatus").textContent=""});
$("#authForm").onsubmit=async e=>{e.preventDefault();const btn=$("#authSubmit"),email=$("#email").value.trim(),password=$("#password").value;loading(btn,true,"CONECTANDO…");const r=authMode==="login"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});loading(btn,false);if(r.error)return $("#authStatus").textContent=authError(r.error);if(authMode==="signup"&&!r.data.session)return $("#authStatus").textContent="Cuenta creada. Revisá tu correo para confirmarla.";showApp(true)};
$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-feed]').forEach(b=>b.onclick=()=>{activeFeed=b.dataset.feed;$$('[data-feed]').forEach(x=>x.classList.toggle("active",x===b));loadFeed()});
$("#topAvatar").onclick=()=>switchView("perfil");$("#searchInput").oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>search(e.target.value),280)};$("#publishForm").onsubmit=publish;$("#filePublishForm").onsubmit=publishFile;$("#videoFile").onchange=previewUploadFile;$$('[data-publish-tab]').forEach(button=>button.onclick=()=>{$$('[data-publish-tab]').forEach(item=>item.classList.toggle("active",item===button));$("#filePublishForm").classList.toggle("hidden",button.dataset.publishTab!=="file");$("#publishForm").classList.toggle("hidden",button.dataset.publishTab!=="link")});$("#liveRefresh").onclick=()=>loadLives(true);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&activeView==="directos")loadLives()});window.addEventListener("online",()=>{if(activeView==="directos")loadLives(true)});
sb.auth.onAuthStateChange((event,session)=>{if(event==="SIGNED_OUT"){currentUser=null;showApp(false)}else if(event==="SIGNED_IN"&&session&&!currentUser)showApp(true)});
sb.auth.getSession().then(r=>showApp(Boolean(r.data.session))).catch(()=>showApp(false));
