(()=>{
  if(new URLSearchParams(location.search).get("ls8teaser")!=="1")return;
  const root=document.createElement("section");root.className="ls8t";root.setAttribute("aria-label","Presentación de LiveScroll 8");root.innerHTML=`<canvas></canvas><div class="ls8t-flash"></div><div class="ls8t-ui"><div class="ls8t-top"><span>LS / TRANSMISIÓN CONFIDENCIAL</span><b>SEÑAL 08</b></div><div class="ls8t-center"><span class="ls8t-kicker">BUSCANDO NUEVAS SEÑALES…</span><h1 class="ls8t-title"><span>Live</span><strong>Scroll</strong><i></i></h1><p class="ls8t-copy">Mantené el dedo o el cursor sobre la señal.</p></div><div class="ls8t-touch">TOCÁ PARA ACTIVAR LA FRECUENCIA</div><button class="ls8t-accept" type="button">ACEPTAR</button><div class="ls8t-progress"><span></span></div></div>`;document.body.appendChild(root);
  const canvas=root.querySelector("canvas"),ctx=canvas.getContext("2d",{alpha:false}),kicker=root.querySelector(".ls8t-kicker"),copy=root.querySelector(".ls8t-copy"),digit=root.querySelector(".ls8t-title i"),progress=root.querySelector(".ls8t-progress span"),touch=root.querySelector(".ls8t-touch"),accept=root.querySelector(".ls8t-accept"),flash=root.querySelector(".ls8t-flash");
  let w=0,h=0,dpr=1,start=performance.now(),pointer={x:0,y:0,active:false},energy=0,audio=null,lastStage=-1,reduced=matchMedia("(prefers-reduced-motion:reduce)").matches;const particles=[];
  function resize(){dpr=Math.min(devicePixelRatio||1,1.6);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);const n=reduced?70:Math.min(420,Math.floor(w*h/2600));particles.length=0;for(let i=0;i<n;i++)particles.push({x:Math.random()*w,y:Math.random()*h,vx:0,vy:0,s:Math.random()*1.7+.3,a:Math.random()*.65+.15,hue:i%7?188:83})}resize();addEventListener("resize",resize,{passive:true});
  function sound(){if(audio)return;try{audio=new (AudioContext||webkitAudioContext)();const osc=audio.createOscillator(),gain=audio.createGain(),filter=audio.createBiquadFilter();osc.type="sine";osc.frequency.value=54;filter.type="lowpass";filter.frequency.value=380;gain.gain.value=.025;osc.connect(filter).connect(gain).connect(audio.destination);osc.start()}catch(_){}}
  function point(e,on){const p=e.touches?.[0]||e;pointer.x=p.clientX;pointer.y=p.clientY;pointer.active=on;if(on){sound();touch.classList.add("is-hot");touch.textContent="FRECUENCIA CONECTADA"}}
  canvas.addEventListener("pointerdown",e=>point(e,true));canvas.addEventListener("pointermove",e=>point(e,e.buttons>0||pointer.active));canvas.addEventListener("pointerup",e=>point(e,false));canvas.addEventListener("pointerleave",e=>point(e,false));canvas.addEventListener("touchstart",e=>point(e,true),{passive:true});canvas.addEventListener("touchmove",e=>point(e,true),{passive:true});canvas.addEventListener("touchend",e=>point(e,false),{passive:true});
  const scenes=[
    {at:0,k:"BUSCANDO NUEVAS SEÑALES…",c:"Mantené el dedo o el cursor sobre la señal.",d:""},
    {at:3,k:"GENERACIÓN ARCHIVADA / 06",c:"Una historia construyó la conexión.",d:"6"},
    {at:6,k:"GENERACIÓN ACTIVA / 07",c:"Otra generación cambió la forma de recorrerla.",d:"7"},
    {at:9,k:"FRECUENCIA DESCONOCIDA",c:"Pero una señal nueva acaba de responder.",d:""},
    {at:12,k:"UNA NUEVA GENERACIÓN",c:"El próximo mundo de LiveScroll está despertando.",d:"8"},
    {at:15,k:"LIVESCROLL 8",c:"PRÓXIMAMENTE · 2027",d:"8"}
  ];
  function setScene(i){if(i===lastStage)return;lastStage=i;const s=scenes[i];kicker.textContent=s.k;copy.textContent=s.c;digit.textContent=s.d;flash.classList.remove("hit");void flash.offsetWidth;flash.classList.add("hit");if(audio){const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=120+i*35;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.35);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.36)}}
  function frame(now){const sec=(now-start)/1000;let scene=0;for(let i=0;i<scenes.length;i++)if(sec>=scenes[i].at)scene=i;setScene(scene);progress.style.width=Math.min(100,sec/18*100)+"%";energy+=(pointer.active?1:-.7);energy=Math.max(0,Math.min(100,energy));const cx=w/2,cy=h/2;ctx.fillStyle=`rgba(2,4,10,${reduced?1:.18})`;ctx.fillRect(0,0,w,h);for(const p of particles){let tx=cx,ty=cy;if(scene===1){const a=particles.indexOf(p)/particles.length*Math.PI*2;tx=cx+Math.cos(a)*Math.min(w,h)*.16;ty=cy+Math.sin(a)*Math.min(w,h)*.22}else if(scene===2){tx=cx+(Math.random()-.5)*w*.2;ty=cy+(Math.random()-.5)*h*.28}else if(scene>=4){const a=particles.indexOf(p)/particles.length*Math.PI*2*3;const r=Math.min(w,h)*(.12+.055*Math.sin(a*1.5));tx=cx+Math.cos(a)*r;ty=cy+Math.sin(a)*r}if(pointer.active){const dx=pointer.x-p.x,dy=pointer.y-p.y,dist=Math.max(80,Math.hypot(dx,dy));p.vx+=dx/dist*.12;p.vy+=dy/dist*.12}else{p.vx+=(tx-p.x)*.0008;p.vy+=(ty-p.y)*.0008}p.vx*=.982;p.vy*=.982;p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=w;if(p.x>w)p.x=0;if(p.y<0)p.y=h;if(p.y>h)p.y=0;ctx.beginPath();ctx.fillStyle=`hsla(${p.hue},95%,${p.hue===83?65:70}%,${p.a})`;ctx.arc(p.x,p.y,p.s+(energy/100)*1.3,0,Math.PI*2);ctx.fill();if(pointer.active&&Math.hypot(pointer.x-p.x,pointer.y-p.y)<115){ctx.beginPath();ctx.strokeStyle="rgba(67,232,255,.08)";ctx.moveTo(p.x,p.y);ctx.lineTo(pointer.x,pointer.y);ctx.stroke()}}if(sec>=17){accept.classList.add("show");touch.style.opacity="0"}if(sec<19&&!root.classList.contains("is-leaving"))requestAnimationFrame(frame)}requestAnimationFrame(frame);
  accept.onclick=()=>{try{localStorage.setItem("ls8_teaser_2027_seen","1")}catch(_){}root.classList.add("is-leaving");if(audio)audio.close();setTimeout(()=>root.remove(),750)};
})();
