(()=>{
  if(new URLSearchParams(location.search).get("ls8teaser")!=="1")return;
  const root=document.createElement("section");root.className="ls8t";root.setAttribute("aria-label","Presentación de LiveScroll 8");root.innerHTML=`<canvas></canvas><div class="ls8t-generations"><b class="ls8t-gen ls8t-gen6">6</b><b class="ls8t-gen ls8t-gen7">7</b></div><div class="ls8t-flash"></div><div class="ls8t-glitch"></div><div class="ls8t-ui"><div class="ls8t-top"><span>LS / TRANSMISIÓN CONFIDENCIAL</span><button class="ls8t-sound" type="button">SONIDO OFF</button></div><div class="ls8t-center"><span class="ls8t-kicker">BUSCANDO NUEVAS SEÑALES…</span><h1 class="ls8t-title"><span>Live</span><strong>Scroll</strong><i></i></h1><p class="ls8t-copy">Mantené el dedo o el cursor sobre la señal.</p></div><div class="ls8t-touch">TOCÁ PARA ACTIVAR LA FRECUENCIA</div><button class="ls8t-accept" type="button">ACEPTAR</button><div class="ls8t-progress"><span></span></div></div>`;document.body.appendChild(root);
  const canvas=root.querySelector("canvas"),ctx=canvas.getContext("2d",{alpha:false}),kicker=root.querySelector(".ls8t-kicker"),copy=root.querySelector(".ls8t-copy"),digit=root.querySelector(".ls8t-title i"),progress=root.querySelector(".ls8t-progress span"),touch=root.querySelector(".ls8t-touch"),accept=root.querySelector(".ls8t-accept"),flash=root.querySelector(".ls8t-flash"),glitch=root.querySelector(".ls8t-glitch");
  let w=0,h=0,dpr=1,start=performance.now(),pointer={x:0,y:0,active:false},energy=0,audioEnabled=false,lastStage=-1,reduced=matchMedia("(prefers-reduced-motion:reduce)").matches;const particles=[],bolts=[],soundBtn=root.querySelector(".ls8t-sound"),soundtrack=new Audio("ls8-audio/teaser-mix.mp3");soundtrack.preload="auto";soundtrack.volume=.9;
  function resize(){dpr=Math.min(devicePixelRatio||1,1.6);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+"px";canvas.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);const n=reduced?70:Math.min(420,Math.floor(w*h/2600));particles.length=0;for(let i=0;i<n;i++)particles.push({x:Math.random()*w,y:Math.random()*h,vx:0,vy:0,s:Math.random()*1.7+.3,a:Math.random()*.65+.15,hue:i%7?188:83})}resize();addEventListener("resize",resize,{passive:true});
  function sound(force){audioEnabled=typeof force==="boolean"?force:true;soundBtn.textContent=audioEnabled?"SONIDO ON":"SONIDO OFF";soundBtn.classList.toggle("on",audioEnabled);if(audioEnabled){soundtrack.currentTime=Math.min(23,(performance.now()-start)/1000);soundtrack.play().catch(()=>{})}else soundtrack.pause()}
  function point(e,on){const p=e.touches?.[0]||e;pointer.x=p.clientX;pointer.y=p.clientY;pointer.active=on;if(on){sound();touch.classList.add("is-hot");touch.textContent="FRECUENCIA CONECTADA"}}
  canvas.addEventListener("pointerdown",e=>point(e,true));canvas.addEventListener("pointermove",e=>point(e,e.buttons>0||pointer.active));canvas.addEventListener("pointerup",e=>point(e,false));canvas.addEventListener("pointerleave",e=>point(e,false));canvas.addEventListener("touchstart",e=>point(e,true),{passive:true});canvas.addEventListener("touchmove",e=>point(e,true),{passive:true});canvas.addEventListener("touchend",e=>point(e,false),{passive:true});
  const scenes=[
    {at:0,k:"BUSCANDO NUEVAS SEÑALES…",c:"Mantené el dedo o el cursor sobre la señal.",d:""},
    {at:3,k:"PORTAL DORADO / GENERACIÓN 06",c:"La generación que construyó la conexión.",d:""},
    {at:7,k:"RUPTURA VIOLETA / GENERACIÓN 07",c:"La generación que cambió el recorrido.",d:""},
    {at:11,k:"COLISIÓN DE GENERACIONES",c:"Dos historias. Una frecuencia imposible.",d:""},
    {at:14,k:"FRECUENCIA DESCONOCIDA",c:"Una nueva señal acaba de responder.",d:""},
    {at:17,k:"UNA NUEVA GENERACIÓN",c:"El próximo mundo de LiveScroll está despertando.",d:"8"},
    {at:20,k:"LIVESCROLL 8",c:"PRÓXIMAMENTE · 2027",d:"8"}
  ];
  function setScene(i){if(i===lastStage)return;lastStage=i;const s=scenes[i];root.className="ls8t"+(i===1?" phase6":i===2?" phase7":i===3?" collision":"");kicker.textContent=s.k;copy.textContent=s.c;digit.textContent=s.d;flash.classList.remove("hit");glitch.classList.remove("hit");void flash.offsetWidth;flash.classList.add("hit");if(i===2||i===3){glitch.classList.add("hit");root.classList.add("shake");setTimeout(()=>root.classList.remove("shake"),450)}if(i===3){for(let b=0;b<10;b++)bolts.push({life:1,a:Math.random()*Math.PI*2})}}
  function frame(now){const sec=(now-start)/1000;let scene=0;for(let i=0;i<scenes.length;i++)if(sec>=scenes[i].at)scene=i;setScene(scene);progress.style.width=Math.min(100,sec/23*100)+"%";energy+=(pointer.active?1:-.7);energy=Math.max(0,Math.min(100,energy));const cx=w/2,cy=h/2;ctx.fillStyle=`rgba(2,4,10,${reduced?1:.16})`;ctx.fillRect(0,0,w,h);particles.forEach((p,pi)=>{let tx=cx,ty=cy;if(scene===1){tx=w*.18+Math.cos(pi)*90;ty=cy+Math.sin(pi)*180;p.hue=43}else if(scene===2){tx=w*.82+Math.sin(pi)*100;ty=cy+Math.cos(pi)*190;p.hue=258}else if(scene===3){tx=cx;ty=cy;p.hue=pi%2?43:258}else if(scene>=4){const a=pi/particles.length*Math.PI*2,r=Math.min(w,h)*(.115+.075*Math.pow(Math.abs(Math.cos(4*a)),7));tx=cx+Math.cos(a)*r;ty=cy+Math.sin(a)*r;p.hue=pi%7?188:83}if(pointer.active){const dx=pointer.x-p.x,dy=pointer.y-p.y,dist=Math.max(80,Math.hypot(dx,dy));p.vx+=dx/dist*.15;p.vy+=dy/dist*.15}else{p.vx+=(tx-p.x)*(scene===3?.004:.0009);p.vy+=(ty-p.y)*(scene===3?.004:.0009)}p.vx*=.98;p.vy*=.98;p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=w;if(p.x>w)p.x=0;if(p.y<0)p.y=h;if(p.y>h)p.y=0;ctx.beginPath();ctx.fillStyle=`hsla(${p.hue},95%,70%,${p.a})`;ctx.arc(p.x,p.y,p.s+(energy/100)*1.5,0,Math.PI*2);ctx.fill();if(pointer.active&&Math.hypot(pointer.x-p.x,pointer.y-p.y)<130){ctx.beginPath();ctx.strokeStyle="rgba(67,232,255,.11)";ctx.moveTo(p.x,p.y);ctx.lineTo(pointer.x,pointer.y);ctx.stroke()}});if(scene>=4){ctx.save();ctx.translate(cx,cy);ctx.rotate(now*.00016);ctx.beginPath();for(let k=0;k<8;k++){const a=k*Math.PI/4-Math.PI/2,r=k%2?Math.min(w,h)*.13:Math.min(w,h)*.2,x=Math.cos(a)*r,y=Math.sin(a)*r;k?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.strokeStyle=`rgba(67,232,255,${.12+energy/900})`;ctx.stroke();ctx.restore()}bolts.forEach(b=>{if(b.life<=0)return;ctx.beginPath();ctx.moveTo(cx,cy);let x=cx,y=cy;for(let j=0;j<7;j++){x+=Math.cos(b.a)*35+(Math.random()-.5)*30;y+=Math.sin(b.a)*35+(Math.random()-.5)*30;ctx.lineTo(x,y)}ctx.strokeStyle=`rgba(180,245,255,${b.life})`;ctx.lineWidth=1.5;ctx.stroke();b.life-=.025});if(sec>=22){accept.classList.add("show");touch.style.opacity="0"}if(sec<26&&!root.classList.contains("is-leaving"))requestAnimationFrame(frame)}requestAnimationFrame(frame);
  soundBtn.onclick=e=>{e.stopPropagation();sound(!audioEnabled)};accept.onclick=()=>{try{localStorage.setItem("ls8_teaser_2027_seen","1")}catch(_){}root.classList.add("is-leaving");soundtrack.pause();soundtrack.currentTime=0;setTimeout(()=>root.remove(),750)};
})();
